server:
  port: '8080'
spring:
  application:
    name: courier-tracking
  datasource:
    url: jdbc:h2:mem:couriertracking
    username: ctracking
    password: ct12345
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html

courier-tracking:
  duration-of-seconds: 60
  distance: 0.1
  earth-radius: 6371.0

